import argparse
import datetime
import dateutil
import torch


def parse_args():
    parser = argparse.ArgumentParser(description="GAN")
    parser.add_argument("--epoch", type=int, default=2)
    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--heads", type=int, default=2)
    parser.add_argument("--depth", type=int, default=2)
    parser.add_argument("--dim", type=int, default=32)
    parser.add_argument("--mlp_dim", type=int, default=128)
    parser.add_argument("--noise_dim", type=int, default=64)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--out_dir", dest="out_dir", type=str, default="./out/")
    parser.add_argument("--model_dir", dest="model_dir", type=str, default="saved_model")
    parser.add_argument("--G_dict", dest="G_dict", type=str, default="")
    parser.add_argument("--C_dict", dest="C_dict", type=str, default="")
    parser.add_argument("--D_dict", dest="D_dict", type=str, default="")
    parser.add_argument("--traj_len", dest="traj_len", type=int, default=8)
    parser.add_argument("--delim", dest="delim", default="\t")
    parser.add_argument("--lr", type=float, default=5e-4, help="adam: learning rate")
    parser.add_argument("--l2_weight", type=float, default=1)
    parser.add_argument("--lr_step", type=int, default=10)
    parser.add_argument("--lr_gamma", type=float, default=0.9)
    parser.add_argument("--agent_num", type=int, default=11)
    parser.add_argument('--learn_prior', action='store_true', default=False)
    parser.add_argument('--ztype', default='gaussian')

    parser.add_argument('--gpu', type=int, default=0)
    parser.add_argument('--seed', type=int, default=0)

    parser.add_argument('--model_names', default="100_nba_train_1_1_")
    parser.add_argument('--model_save_dir', default='saved_models/nba')
    parser.add_argument('--vis', action='store_true', default=False)
    parser.add_argument('--traj_scale', type=int, default=1)
    parser.add_argument('--sample_k', type=int, default=20)
    parser.add_argument('--past_length', type=int, default=5)
    parser.add_argument('--future_length', type=int, default=10)

    parser.add_argument('--agent',  nargs='+', type=int, default=[0 , 2])
    parser.add_argument('--target', default=[[[12,10],[5,14], [0,0], [5,5],[8,11]]])
    parser.add_argument('--method', default="mean")
    parser.add_argument('--length', type=int, default=120)
    parser.add_argument('--mode', type=str, default="train")
    parser.add_argument('--GAN_models', type=str, default="")
    parser.add_argument('--save_every', type=int, default=2)
    parser.add_argument('--training_type', type=str, default="test")
    parser.add_argument('--iternum_print', type=int, default=500)
    parser.add_argument("--edge_num", type=int, default=12)
    parser.add_argument("--mission_coef", type=float, default=0.7)
    parser.add_argument("--pred_coef", type=float, default=0.3)
    parser.add_argument("--mission_method", type=str, default="mean")
    parser.add_argument("--dataset", type=str, default="nba")
    parser.add_argument("--saved_models_GM", default="mission_aware30_None_nba_train_1_1_0.2")
    parser.add_argument("--saved_models_DIS", default="D_100_0_sampler")
    parser.add_argument("--saved_models_GAN_GM", default="GM__None_train_1_250_0_0.2_")
    parser.add_argument("--saved_models_GAN_DIS", default="D__None_train_1_250_0_0.2_")
    parser.add_argument("--saved_models_GAN_SM", default="SM__None_train_1_100_0_0.2_")
    parser.add_argument("--saved_models_GAN_DIS_SM", default="D__None_train_1_100_0_0.2_")
    parser.add_argument("--saved_models_SAM", default="G__None_train_1_300_0_False_")
    parser.add_argument("--saved_models_SM", default="SM__None_test_False_10_0_0.2_")
    parser.add_argument("--saved_models_non_trained_DIS", default="D__None_test_30_0_GM__None_train_1_250_0_0.2__")
    parser.add_argument("--saved_models_non_trained_DIS_SM", default="D__None_test_30_0_SM__None_train_1_100_0_0.2__")
    parser.add_argument("--test_mlp", default=False, action="store_true")
    parser.add_argument("--classifier_method", type=str, default="sampler_selected")
    parser.add_argument('--min_clip', type=float, default=2.0)
    parser.add_argument('--hidden_dim', type=int, default=64)
    parser.add_argument('--hyper_scales', nargs='+', type=int,
                        default=[5, 11])
    parser.add_argument('--num_decompose', type=int, default=2)
    parser.add_argument('--zdim', type=int, default=32)
    parser.add_argument('--alpha', type=float, default=1)
    parser.add_argument("--n_critic", type=int, default=5, help="Number of D updates per G update")
    parser.add_argument('--div_p', type=float, default=6)
    parser.add_argument('--div_k', type=float, default=2.0)
    parser.add_argument('--mission_buffer', type=float, default=2.0)
    parser.add_argument('--longest_distance', type=float, default=27, help="the farest distance for nba player in 4 seconds to run")
    parser.add_argument('--sim_num', type=int, default=100)
    parser.add_argument('--mission_num', type=int, default=8)
    parser.add_argument('--testing',action='store_true', default=False)
    parser.add_argument('--info', type=str, default="")
    parser.add_argument('--max_covert', type=int, default=5)
    parser.add_argument('--scene', type=str, default="")
    parser.add_argument('--replace_threshold', type=float, default=2)
    parser.add_argument('--sdd_scene', type=int, default=None)
    parser.add_argument('--how_far', type=float, default=0.2)
    parser.add_argument('--pca_comp', type=int, default=2)
    parser.add_argument('--direction_coef', type=float, default=2.5)
    parser.add_argument('--disc_type', type=str, default='groupnet-gan')
    parser.add_argument('--epoch_continue', type=int, default=0)
    parser.add_argument('--agents_to_plot', type=int, default=1)

    args = parser.parse_args()
    args.device = "cuda" if torch.cuda.is_available() else "cpu"
    if "timestamp" not in args:
        args.timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    return args


if __name__ == "__main__":
    print(parse_args())
